sudo: required
language: c
dist: xenial
compiler:
  - clang
  - gcc
cache: ccache
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libslurm-dev
before_script:
  - export PATH=/usr/lib/ccache:$PATH
  - sudo mount -t tmpfs -o size=1024m tmpfs /tmp
script:
  - make > /dev/null
