sudo: required
language: c
dist: trusty
addons:
  apt:
    packages:
    - slurm-dev
compiler:
  - clang
  - gcc
cache: ccache
before_script:
  - export PATH=/usr/lib/ccache:$PATH
  - sudo mount -t tmpfs -o size=1024m tmpfs /tmp
script:
  - make -j > /dev/null
